### ISSUE TITLE
[0.7.2] GameError

### ISSUE THREAD

**Issue by PGHJA991id12** [LANCommander/LANCommander#65]
Primary actions no longer work in version 0.7.2. Non-primary actions are functional, though.

![image](https://github.com/LANCommander/LANCommander/assets/168939183/aa1829a9-82d8-40d0-b779-6eaca78c025c)

**Comment by PGHJA991id12** [comment]
Oh and the Before Start / After Stop script types do not run on expansions/mods. Likewise the Name Change scripts I have on the expansions/mods doesn't work either. Probably goes for install and uninstall scripts as well.

**Comment by pathartl** [comment]
Please try v0.7.3

**Comment by pathartl** [comment]
> First of: Running the base game causes the expansion/mod scripts to run (Before Start/After Stop) which is not correct.
This is a limitation of the Playnite API. When launching the game there is no context to which action was used.

> Upon starting Playnite or refreshing the games list, it says it's downloading a total of 26 metadata, but I only have 18 games in my list.
The LANCommander extension does all of its data population on import and does not implement a metadata provider. The progress bar you're seeing is probably the built in IGDB extension.

**Comment by PGHJA991id12** [comment]
Alright! Then everything is in working order. Thank you very much! :D
